### ISSUE TITLE
Remove imports of javax.security.auth.message.** classes

### ISSUE THREAD

**Issue by wmhopkins** [javaee/security-api#54]
Several classes in the API import javax.security.auth.message.ServletAuthModule or javax.security.auth.message.MessageInfo.

The MessageInfo references appear to be necessary, as they occur in HttpMessageContext and HttpMessageContextWrapper. (To achieve the goal of no direct dependencies on JASPIC, it seems we should have mimic'd this class in addition to AuthStatus and AuthException -- or simply allowed all three dependencies, since HAM is inextricably tied to JASPIC anyway.)

The ServerAuthModule references are all in javadoc, however, and it might be better to remove the imports and instead reference the FQN for ServerAuthModule in the javadoc. That should avoid compile and load time dependencies on JASPIC from APIs that don't have any real dependency on JASPIC, like the IdentityStore classes.

**Comment by wmhopkins** [comment]
@arjantijms, what do you think about this one? Am I right that the javadoc references are ephemeral, will not be present in the compiled .class file, and therefore will not create a load-time dependency in the same way that an import statement does?

**Comment by arjantijms** [comment]
An import is a namespace reference anyway, and not an actual "import" (as-in "include") as the name might suggest.

If someone feels strongly about removing them from javadoc I don't think many people would mind, I certainly would not mind much.

The MessageInfo type was not mimic'd before as it's not a type we'd normally use much. It's provided as an option for code that needs to go down to the JASPIC level, and then mostly to obtain and/or set "hints" in the map it provides. The so-called response and request messages are the http servlet request and response in the HAM case, so basically we mimic these already.

If we want a 100% JASPIC less dependency (wrt its imports) we could still address this if people feel strongly about it.

The getter for MessageInfo could be replaced by Object (people could then cast it themselves), and additionally the likely most frequently used part of it (the map) could quite easily become a getMessageInfoMap() method on the HttpMessageContext.

So it depends a little on how strongly people feel about this really.

**Comment by wmhopkins** [comment]
It's my understanding (quite possibly wrong) that loading/linking a class that has a particular import will fail if the imported name cannot be found in classpath. Is that not the case?

I think it's too late to change the actual interface, although I hate to see it go out with some "inconsistency" -- AuthStatus/AuthException mimic'd, precisely to avoid a hard dependency on JASPIC, while MessageInfo is not mimic'd. In hindsight, I think it might have been better, instead, to retain the use of AuthStatus/AuthException in the HAM interface, because HAM is explicitly tied to JASPIC anyway, and might as well use the native types. But again, I don't think we can change the API at this point -- too much downstream impact on GF and TCK.

WRT the javadoc, I'm not suggesting we remove the references, what I'm suggesting is that we remove the imports, and instead use FQNs as the {@link} parameter for any JASPIC classes referenced by the javadoc. My hypothesis (haven't had time to test) is that, unlike import statements, which are retained in the .class file, FQNs in javadoc {@link} references will not be retained, or will be retained only as compiled comments, and thus will be ignored during linking/loading.

I don't mind so much if javax.security.enterprise.authenticationmechanism.http has a dependency on JASPIC, but it seems unnecessary for javax.security.enterprise.identitystore to have that dependency.

This is a small thing, but if changing "import FQN ... {@link ShortName}" to "{@link FQN} (no import) would actually remove the load/link dependency I'd want to make the change.

**Comment by arjantijms** [comment]
>This is a small thing, but if changing "import FQN ... {@link ShortName}" to "{@link FQN} (no import) would actually remove the load/link dependency I'd want to make the change.

I'm pretty sure it makes no difference whatsoever. It's just a namespace import for the compiler. Runtime issues only occur if the resource (i.e. class) it represents is actually attempted to be loaded.

**Comment by arjantijms** [comment]
>But again, I don't think we can change the API at this point -- too much downstream impact on GF and TCK.

Okay, then it is what it is I guess. Should someone (GF, TCK, whoever) changes their mind, let me know and I can change it.

**Comment by arjantijms** [comment]
Btw, for an authoritative answer to this:

https://docs.oracle.com/javase/specs/jls/se8/html/jls-7.html#jls-7.5

**Comment by wmhopkins** [comment]
Nevermind, then. Thanks for looking into it.
