### ISSUE TITLE
Source formatting

### ISSUE THREAD

**Issue by ggam** [javaee/security-api#58]
Some classes have weird formatting. See for example https://github.com/javaee/security-api/blob/master/src/main/java/javax/security/enterprise/SecurityContext.java

Someone should apply a recursive autoformat on the project before it goes final. The only problem could be merge conflicts, so I think this should be basically the last thing to do.

**Comment by wmhopkins** [comment]
@ggam -- Have you noticed others? Do you have a tool to suggest?

**Comment by ggam** [comment]
I always use NetBeans formatter, but I think Arjan has been formatting with Eclipse, which seems to group imports in groups by top-level package. Any tool will work I guess.

**Comment by wmhopkins** [comment]
I use eclipse as well, it can format source but doesn't have an automated or recursive mode that I'm aware of, it's file by file (it also makes some choices I'm not fond of, although that's probably adjustable if I took the time to figure out how).

**Comment by wmhopkins** [comment]
This is a good idea, but there's no time to get it done.

**Comment by ggam** [comment]
@wmhopkins As I understand, no more changes can be done now, right? I could create a PR but I think at this stage it couldn't be accepted.

Anyway, formatting of APIs can be done for the next version.
