### ISSUE TITLE
Update built-in identity stores (Database, LDAP) to document required credential type support

### ISSUE THREAD

**Issue by wmhopkins** [javaee/security-api#60]
Document that built-in stores must handle `UsernamePasswordCredential`, and may handle other types.

**Comment by arjantijms** [comment]
For now indeed only `UsernamePasswordCredential`. Other credentials may require other attributes on the configuration annotations, plus the RI has not implemented support for them now.

Theoretically the `CallerOnlyCredential` should be easy to support for at least the database identity store, but I think it's too late in the process now to still add this.

**Comment by wmhopkins** [comment]
Done.
